name: naturale_app
description: An app for naturale

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.8
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  provider: ^6.0.5
  flutter_local_notifications: ^12.0.4
  flutter_markdown: ^0.6.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_app_name: ^0.1.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/img/logo.png"

flutter_app_name:
  name: "Naturale"
