// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyoArEQayGRjrBxnDYq5EC7JGpHZWriJ8',
    appId: '1:1016108643827:web:1df2c689d7251093de4e86',
    messagingSenderId: '1016108643827',
    projectId: 'naturale-app',
    authDomain: 'naturale-app.firebaseapp.com',
    storageBucket: 'naturale-app.appspot.com',
    measurementId: 'G-XY7XVEGSK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsh5ADvegqY2m1bl2nua6ppk_Os8LmjLU',
    appId: '1:1016108643827:android:73e9dc5e60db107cde4e86',
    messagingSenderId: '1016108643827',
    projectId: 'naturale-app',
    storageBucket: 'naturale-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjBldJ6-TegaxuZV__kyiJQaQtI0ibZLk',
    appId: '1:1016108643827:ios:d747712552e2f0efde4e86',
    messagingSenderId: '1016108643827',
    projectId: 'naturale-app',
    storageBucket: 'naturale-app.appspot.com',
    iosClientId:
        '1016108643827-n9cnp15c8ih1ijqudo87hcp54fn032d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.naturaleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjBldJ6-TegaxuZV__kyiJQaQtI0ibZLk',
    appId: '1:1016108643827:ios:d747712552e2f0efde4e86',
    messagingSenderId: '1016108643827',
    projectId: 'naturale-app',
    storageBucket: 'naturale-app.appspot.com',
    iosClientId:
        '1016108643827-n9cnp15c8ih1ijqudo87hcp54fn032d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.naturaleApp',
  );
}
